### ISSUE TITLE
cecil serve : localhost refused to connect

### ISSUE THREAD

**Issue by happytodev** [Cecilapp/Cecil#1868]
### Describe the bug

Hello Arnaud,

With a simple install of Cecil when I started the server with `cecil serve`, I have this

<img width="848" alt="image" src="https://github.com/Cecilapp/Cecil/assets/425998/246fec64-02e5-4777-b265-6feac140e378">

I'm on Mac, I've stopped all my valet services to be sure of no interference.

I tried with others ports.

Nothing special for me in verbose mode and no log in .cecil

I appreciate if you can give me some advice ;-)

PS : the build command works as expected

### To reproduce

1. create a new install
2. Start the server with `cecil serve`
3. error

### Expected behavior

I wish to have a normal behaviour of `cecil serve` to show the modification I made.

### Version

8

### Operating System

MAC OS

### Relevant log output

No log in .cecil folder

**Comment by ArnaudLigny** [comment]
Hello @happytodev, it can occur when PHP is already used by another process. Could you run Cecil in verbose mode (`cecil serve -vvv`) and share the console log?

**Comment by happytodev** [comment]
Here it is : 

Box Requirements Checker
========================

> Using PHP 8.2.14
> PHP is not using any php.ini file.

> Checking Box requirements:
  ✔ This application requires a PHP version matching "^8.1||^8.2||^8.3".
  ✔ This application requires the extension "zlib".
  ✔ This application requires the extension "fileinfo".
  ✔ The package "intervention/image" requires the extension "fileinfo".
  ✔ The package "spatie/image-optimizer" requires the extension "fileinfo".
  ✔ This application requires the extension "gd".
  ✔ The package "humbug/box" requires the extension "phar".
  ✔ The package "humbug/box" requires the extension "sodium".
  ✔ The package "matthiasmullie/minify" requires the extension "pcre".
  ✔ The package "matthiasmullie/path-converter" requires the extension "pcre".
  ✔ The package "nikic/php-parser" requires the extension "tokenizer".
  ✔ The package "phpdocumentor/reflection-docblock" requires the extension
"filter".
  ✔ The package "scrivo/highlight.php" requires the extension "json".
  ✔ The package "scssphp/scssphp" requires the extension "json".
  ✔ The package "voku/html-min" requires the extension "dom".
  ✔ The package "voku/simple_html_dom" requires the extension "dom".
  ✔ The package "voku/simple_html_dom" requires the extension "libxml".
  ✔ The package "voku/simple_html_dom" requires the extension "simplexml".
  ✔ The package "symfony/service-contracts" conflicts with the extension "psr".


 [OK] Your system is ready to run the application.


Process: /Users/happytodev/Library/Application Support/Herd/bin/php82 /usr/local/bin/cecil build /Users/happytodev/Sites/fhblogcecil --config /Users/happytodev/Sites/fhblogcecil/config.yml -vvv
Building website...
Path: /Users/happytodev/Sites/fhblogcecil
Config: /Users/happytodev/Sites/fhblogcecil/config.yml
Cache: /Users/happytodev/Sites/fhblogcecil/.cache
1. Loading pages
[12/12] Files loaded
Loading pages done in 2 ms (201.11 kb)
2. Creating pages
[ 1/12] Page "about" created
[ 2/12] Page "authoring-content" created
[ 3/12] Page "blog/post-1" created
[ 4/12] Page "blog/post-2" created
[ 5/12] Page "blog/post-3" created
[ 6/12] Page "blog/post-4" created
[ 7/12] Page "blog/post-5" created
[ 8/12] Page "blog/post-6" created
[ 9/12] Page "index" created
[10/12] Page "lorem" created
[11/12] Page "section/page-1" created
[12/12] Page "section/page-2" created
Creating pages done in 7 ms (1.25 mb)
3. Converting pages
[ 1/12] Page "about" converted
Asset "/Users/happytodev/Sites/fhblogcecil/_site/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
[ 2/12] Page "authoring-content" converted
[ 3/12] Page "blog/post-1" converted
[ 4/12] Page "blog/post-2" converted
[ 5/12] Page "blog/post-3" converted
[ 6/12] Page "blog/post-4" converted
[ 7/12] Page "blog/post-5" converted
[ 8/12] Page "blog/post-6" converted
[ 9/12] Page "index" converted
[10/12] Page "lorem" converted
[11/12] Page "section/page-1" converted
[12/12] Page "section/page-2" converted
Converting pages done in 325 ms (4.39 mb)
4. Creating taxonomies
[1/2] Vocabularies collection created
[2/2] Terms collection created
Creating taxonomies done in 1 ms (11.52 kb)
5. Generating pages
[1/9] 4 "DefaultPages" pages generated and 0 pages updated
[2/9] 0 "VirtualPages" pages generated and 0 pages updated
[3/9] 0 "ExternalBody" pages generated and 0 pages updated
[4/9] 2 "Section" pages generated and 8 pages updated
[5/9] 3 "Taxonomy" pages generated and 0 pages updated
[6/9] 0 "Homepage" pages generated and 1 pages updated
[7/9] 3 "Pagination" pages generated and 2 pages updated
[8/9] 2 "Alias" pages generated and 0 pages updated
[9/9] 0 "Redirect" pages generated and 0 pages updated
Generating pages done in 2 ms (206.44 kb)
6. Creating menus
[1/5] Page menu entry "main (en) > about" created {name: About, weight: 999}
[2/5] Page menu entry "main (en) > authoring-content" created {name: Authoring Content, weight: 300}
[3/5] Page menu entry "main (en) > index" created {name: Home, weight: 0}
[4/5] Page menu entry "main (en) > blog" created {name: Blog, weight: 100}
[5/5] Page menu entry "main (en) > section" created {name: Section, weight: 110}
Creating menus done in 0 ms (14.15 kb)
7. Copying static
[1/1] Files copied
Copying static done in 2 ms (1016 b)
8. Rendering pages
Translation loader for format "yaml" found
Translation loader for format "mo" found
Intl extension is loaded
Output post processor "Cecil\Renderer\PostProcessor\GeneratorMetaTag" loaded
Output post processor "Cecil\Renderer\PostProcessor\HtmlExcerpt" loaded
Output post processor "Cecil\Renderer\PostProcessor\MarkdownLink" loaded
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/32/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/57/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/76/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/96/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/128/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/192/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/228/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/196/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/120/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/152/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/180/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/fhblogcecil/_site/assets/thumbnails/1200/cecil-card.c0bc77e003455fafeb15f3072e857d85.png" saved
[ 1/26] Page "about" rendered with [cecil:_default/page.html.twig]
[ 2/26] Page "authoring-content" rendered with [cecil:_default/page.html.twig]
[ 3/26] Page "blog/post-1" rendered with [site:blog/page.html.twig]
[ 4/26] Page "blog/post-2" rendered with [site:blog/page.html.twig]
[ 5/26] Page "blog/post-3" rendered with [site:blog/page.html.twig]
[ 6/26] Page "blog/post-4" rendered with [site:blog/page.html.twig]
[ 7/26] Page "blog/post-5" rendered with [site:blog/page.html.twig]
[ 8/26] Page "blog/post-6" rendered with [site:blog/page.html.twig]
[ 9/26] Page "index" rendered with [site:index.html.twig, cecil:_default/list.atom.twig]
[10/26] Page "lorem" rendered with [cecil:_default/page.html.twig]
[11/26] Page "section/page-1" rendered with [cecil:_default/page.html.twig]
[12/26] Page "section/page-2" rendered with [cecil:_default/page.html.twig]
[13/26] Page "404" rendered with [cecil:_default/404.html.twig]
[14/26] Page "robots" rendered with [cecil:_default/robots.txt.twig]
[15/26] Page "sitemap" rendered with [cecil:_default/sitemap.xml.twig]
[16/26] Page "xsl/atom" rendered with [cecil:_default/feed.xsl.twig]
[17/26] Page "blog" rendered with [site:blog/list.html.twig, cecil:_default/list.atom.twig]
[18/26] Page "section" rendered with [cecil:_default/list.html.twig, cecil:_default/list.atom.twig]
[19/26] Page "tags/tag-1" rendered with [cecil:_default/list.html.twig, cecil:_default/list.atom.twig]
[20/26] Page "tags/tag-2" rendered with [cecil:_default/list.html.twig, cecil:_default/list.atom.twig]
[21/26] Page "tags" rendered with [cecil:_default/vocabulary.html.twig]
[22/26] Page "index/page/2" rendered with [site:index.html.twig]
[23/26] Page "index/page/3" rendered with [site:index.html.twig]
[24/26] Page "blog/page/2" rendered with [site:blog/list.html.twig]
[25/26] Page "page/1" rendered with [cecil:_default/redirect.html.twig]
[26/26] Page "blog/page/1" rendered with [cecil:_default/redirect.html.twig]
Rendering pages done in 290 ms (7.56 mb)
9. Saving pages
[ 1/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/about/index.html" saved
[ 2/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/authoring-content/index.html" saved
[ 3/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/blog/post-1/index.html" saved
[ 4/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/blog/post-2/index.html" saved
[ 5/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/blog/post-3/index.html" saved
[ 6/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/blog/post-4/index.html" saved
[ 7/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/blog/post-5/index.html" saved
[ 8/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/blog/post-6/index.html" saved
[ 9/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/index.html, /Users/happytodev/Sites/fhblogcecil/_site/atom.xml" saved
[10/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/lorem/index.html" saved
[11/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/section/page-1/index.html" saved
[12/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/section/page-2/index.html" saved
[13/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/404.html" saved
[14/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/robots.txt" saved
[15/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/sitemap.xml" saved
[16/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/xsl/atom.xsl" saved
[17/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/blog/index.html, /Users/happytodev/Sites/fhblogcecil/_site/blog/atom.xml" saved
[18/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/section/index.html, /Users/happytodev/Sites/fhblogcecil/_site/section/atom.xml" saved
[19/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/tags/tag-1/index.html, /Users/happytodev/Sites/fhblogcecil/_site/tags/tag-1/atom.xml" saved
[20/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/tags/tag-2/index.html, /Users/happytodev/Sites/fhblogcecil/_site/tags/tag-2/atom.xml" saved
[21/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/tags/index.html" saved
[22/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/page/2/index.html" saved
[23/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/page/3/index.html" saved
[24/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/blog/page/2/index.html" saved
[25/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/page/1/index.html" saved
[26/26] File(s) "/Users/happytodev/Sites/fhblogcecil/_site/blog/page/1/index.html" saved
Saving pages done in 12 ms (352 b)
Built in 674 ms (14.04 mb)
Done! 🎉
Starting server (localhost:8000)...

**Comment by burkaslarry** [comment]
resolved ?

**Comment by happytodev** [comment]
> resolved ?

No. Waiting for Arnaud ;-)

**Comment by ArnaudLigny** [comment]
Hello guys, sorry for the delay: I have carried out several tests, on different environments (Windows and macOS), with different versions of Cecil, and I cannot reproduce the problem...

From my point of view the only case where the local server is unavailable is if another server is already launched in the same context (host + port).

**Comment by happytodev** [comment]
> Hello guys, sorry for the delay: I have carried out several tests, on different environments (Windows and macOS), with different versions of Cecil, and I cannot reproduce the problem...
> 

No need to apologies Arnaud ! 

> From my point of view the only case where the local server is unavailable is if another server is already launched in the same context (host + port).

The point is, even if I launch with --port another port, the result still the same.

I will try on another PC, but I don't understand. I'm really frustrated because Cecil seems to have everything I need.

**Comment by ArnaudLigny** [comment]
The Cecil _serve_ command is based on the [PHP built-in web server](https://www.php.net/manual/en/features.commandline.webserver.php), so could you try to run the following command and tell me if http://localhost:8000 is available from your web browser?

```bash
php -S localhost:8000
```

**Comment by ArnaudLigny** [comment]
Hello @happytodev, to help us to found the origin of the problem I released a new version (8.3.0) with more logs: https://github.com/Cecilapp/Cecil/pull/1879.

So, could you update Cecil `cecil self-update` then run `cecil serve`, and check:
1. if there is an explicit message in your terminal?
2. an `.cecil/errors.log` file in your project?

Thank you.

**Comment by happytodev** [comment]
Sorry to generate more work for you.

The `cecil serve` command answers me "Server is not ready"

<img width="395" alt="image" src="https://github.com/Cecilapp/Cecil/assets/425998/221464b5-9a4c-4e09-8046-d1cfd5530e99">

And in the log, I have this line :

`sh: /Users/happytodev/Library/Application: No such file or directory` 

Another test I made. I tried cecil on windows and the server starts normally and the site is displayed.

So, I think it's specific to MacOS.

Hope this help you to understand what's wrong.

**Comment by ArnaudLigny** [comment]
OK, OK, can you do a last test: running the server in debug mode (`cecil serve -vvv`) and copy/paste the "Server process: xxx" terminal line? Thx.

**Comment by happytodev** [comment]
Here it is : 

`➜  cecil cecil serve -vvv

Box Requirements Checker
========================

> Using PHP 8.2.14
> PHP is not using any php.ini file.

> Checking Box requirements:
  ✔ This application requires a PHP version matching "^8.1||^8.2||^8.3".
  ✔ This application requires the extension "zlib".
  ✔ This application requires the extension "fileinfo".
  ✔ The package "intervention/image" requires the extension "fileinfo".
  ✔ The package "spatie/image-optimizer" requires the extension "fileinfo".
  ✔ This application requires the extension "gd".
  ✔ The package "humbug/box" requires the extension "phar".
  ✔ The package "humbug/box" requires the extension "sodium".
  ✔ The package "matthiasmullie/minify" requires the extension "pcre".
  ✔ The package "matthiasmullie/path-converter" requires the extension "pcre".
  ✔ The package "nikic/php-parser" requires the extension "tokenizer".
  ✔ The package "phpdocumentor/reflection-docblock" requires the extension "filter".
  ✔ The package "scrivo/highlight.php" requires the extension "json".
  ✔ The package "scssphp/scssphp" requires the extension "json".
  ✔ The package "voku/html-min" requires the extension "dom".
  ✔ The package "voku/simple_html_dom" requires the extension "dom".
  ✔ The package "voku/simple_html_dom" requires the extension "libxml".
  ✔ The package "voku/simple_html_dom" requires the extension "simplexml".
  ✔ The package "symfony/service-contracts" conflicts with the extension "psr".


 [OK] Your system is ready to run the application.


Build process: /Users/happytodev/Library/Application Support/Herd/bin/php82 /opt/homebrew/bin/cecil build /Users/happytodev/Sites/cecil --config /Users/happytodev/Sites/cecil/config.yml -vvv
Building website...
Path: /Users/happytodev/Sites/cecil
Config: /Users/happytodev/Sites/cecil/config.yml
Cache: /Users/happytodev/Sites/cecil/.cache
1. Loading pages
[11/11] Files loaded
Loading pages done in 1 ms (201.5 kb)
2. Creating pages
[ 1/11] Page "about" created
[ 2/11] Page "authoring-content" created
[ 3/11] Page "blog/post-1" created
[ 4/11] Page "blog/post-2" created
[ 5/11] Page "blog/post-3" created
[ 6/11] Page "blog/post-4" created
[ 7/11] Page "blog/post-5" created
[ 8/11] Page "blog/post-6" created
[ 9/11] Page "index" created
[10/11] Page "section/page-1" created
[11/11] Page "section/page-2" created
Creating pages done in 5 ms (1.25 mb)
3. Converting pages
[ 1/11] Page "about" converted
Asset "/Users/happytodev/Sites/cecil/_site/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
[ 2/11] Page "authoring-content" converted
[ 3/11] Page "blog/post-1" converted
[ 4/11] Page "blog/post-2" converted
[ 5/11] Page "blog/post-3" converted
[ 6/11] Page "blog/post-4" converted
[ 7/11] Page "blog/post-5" converted
[ 8/11] Page "blog/post-6" converted
[ 9/11] Page "index" converted
[10/11] Page "section/page-1" converted
[11/11] Page "section/page-2" converted
Converting pages done in 245 ms (4.39 mb)
4. Creating taxonomies
[1/2] Vocabularies collection created
[2/2] Terms collection created
Creating taxonomies done in 0 ms (11.63 kb)
5. Generating pages
[1/9] 4 "DefaultPages" pages generated and 0 pages updated
[2/9] 0 "VirtualPages" pages generated and 0 pages updated
[3/9] 0 "ExternalBody" pages generated and 0 pages updated
[4/9] 2 "Section" pages generated and 8 pages updated
[5/9] 3 "Taxonomy" pages generated and 0 pages updated
[6/9] 0 "Homepage" pages generated and 1 pages updated
[7/9] 2 "Pagination" pages generated and 2 pages updated
[8/9] 2 "Alias" pages generated and 0 pages updated
[9/9] 0 "Redirect" pages generated and 0 pages updated
Generating pages done in 2 ms (202.71 kb)
6. Creating menus
[1/5] Page menu entry "main (en) > about" created {name: About, weight: 999}
[2/5] Page menu entry "main (en) > authoring-content" created {name: Authoring Content, weight: 300}
[3/5] Page menu entry "main (en) > index" created {name: Home, weight: 0}
[4/5] Page menu entry "main (en) > blog" created {name: Blog, weight: 100}
[5/5] Page menu entry "main (en) > section" created {name: Section, weight: 110}
Creating menus done in 0 ms (14.23 kb)
7. Copying static
[1/1] Files copied
Copying static done in 2 ms (936 b)
8. Rendering pages
Translation loader for format "yaml" found
Translation loader for format "mo" found
PHP Intl extension is loaded
Output post processor "GeneratorMetaTag" loaded
Output post processor "HtmlExcerpt" loaded
Output post processor "MarkdownLink" loaded
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/32/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/57/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/76/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/96/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/128/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/192/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/228/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/196/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/120/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/152/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/180/favicon.c1af8a129a0cde81f9b94ffbf452e10b.png" saved
Asset "/Users/happytodev/Sites/cecil/_site/assets/thumbnails/1200/cecil-card.c0bc77e003455fafeb15f3072e857d85.png" saved
[ 1/24] Page "about" rendered with [cecil:_default/page.html.twig]
[ 2/24] Page "authoring-content" rendered with [cecil:_default/page.html.twig]
[ 3/24] Page "blog/post-1" rendered with [site:blog/page.html.twig]
[ 4/24] Page "blog/post-2" rendered with [site:blog/page.html.twig]
[ 5/24] Page "blog/post-3" rendered with [site:blog/page.html.twig]
[ 6/24] Page "blog/post-4" rendered with [site:blog/page.html.twig]
[ 7/24] Page "blog/post-5" rendered with [site:blog/page.html.twig]
[ 8/24] Page "blog/post-6" rendered with [site:blog/page.html.twig]
[ 9/24] Page "index" rendered with [site:index.html.twig, cecil:_default/list.atom.twig]
[10/24] Page "section/page-1" rendered with [cecil:_default/page.html.twig]
[11/24] Page "section/page-2" rendered with [cecil:_default/page.html.twig]
[12/24] Page "404" rendered with [cecil:_default/404.html.twig]
[13/24] Page "robots" rendered with [cecil:_default/robots.txt.twig]
[14/24] Page "sitemap" rendered with [cecil:_default/sitemap.xml.twig]
[15/24] Page "xsl/atom" rendered with [cecil:_default/feed.xsl.twig]
[16/24] Page "blog" rendered with [site:blog/list.html.twig, cecil:_default/list.atom.twig]
[17/24] Page "section" rendered with [cecil:_default/list.html.twig, cecil:_default/list.atom.twig]
[18/24] Page "tags/tag-1" rendered with [cecil:_default/list.html.twig, cecil:_default/list.atom.twig]
[19/24] Page "tags/tag-2" rendered with [cecil:_default/list.html.twig, cecil:_default/list.atom.twig]
[20/24] Page "tags" rendered with [cecil:_default/vocabulary.html.twig]
[21/24] Page "index/page/2" rendered with [site:index.html.twig]
[22/24] Page "blog/page/2" rendered with [site:blog/list.html.twig]
[23/24] Page "page/1" rendered with [cecil:_default/redirect.html.twig]
[24/24] Page "blog/page/1" rendered with [cecil:_default/redirect.html.twig]
Rendering pages done in 167 ms (5.96 mb)
9. Saving pages
[ 1/24] File(s) "/Users/happytodev/Sites/cecil/_site/about/index.html" saved
[ 2/24] File(s) "/Users/happytodev/Sites/cecil/_site/authoring-content/index.html" saved
[ 3/24] File(s) "/Users/happytodev/Sites/cecil/_site/blog/post-1/index.html" saved
[ 4/24] File(s) "/Users/happytodev/Sites/cecil/_site/blog/post-2/index.html" saved
[ 5/24] File(s) "/Users/happytodev/Sites/cecil/_site/blog/post-3/index.html" saved
[ 6/24] File(s) "/Users/happytodev/Sites/cecil/_site/blog/post-4/index.html" saved
[ 7/24] File(s) "/Users/happytodev/Sites/cecil/_site/blog/post-5/index.html" saved
[ 8/24] File(s) "/Users/happytodev/Sites/cecil/_site/blog/post-6/index.html" saved
[ 9/24] File(s) "/Users/happytodev/Sites/cecil/_site/index.html, /Users/happytodev/Sites/cecil/_site/atom.xml" saved
[10/24] File(s) "/Users/happytodev/Sites/cecil/_site/section/page-1/index.html" saved
[11/24] File(s) "/Users/happytodev/Sites/cecil/_site/section/page-2/index.html" saved
[12/24] File(s) "/Users/happytodev/Sites/cecil/_site/404.html" saved
[13/24] File(s) "/Users/happytodev/Sites/cecil/_site/robots.txt" saved
[14/24] File(s) "/Users/happytodev/Sites/cecil/_site/sitemap.xml" saved
[15/24] File(s) "/Users/happytodev/Sites/cecil/_site/xsl/atom.xsl" saved
[16/24] File(s) "/Users/happytodev/Sites/cecil/_site/blog/index.html, /Users/happytodev/Sites/cecil/_site/blog/atom.xml" saved
[17/24] File(s) "/Users/happytodev/Sites/cecil/_site/section/index.html, /Users/happytodev/Sites/cecil/_site/section/atom.xml" saved
[18/24] File(s) "/Users/happytodev/Sites/cecil/_site/tags/tag-1/index.html, /Users/happytodev/Sites/cecil/_site/tags/tag-1/atom.xml" saved
[19/24] File(s) "/Users/happytodev/Sites/cecil/_site/tags/tag-2/index.html, /Users/happytodev/Sites/cecil/_site/tags/tag-2/atom.xml" saved
[20/24] File(s) "/Users/happytodev/Sites/cecil/_site/tags/index.html" saved
[21/24] File(s) "/Users/happytodev/Sites/cecil/_site/page/2/index.html" saved
[22/24] File(s) "/Users/happytodev/Sites/cecil/_site/blog/page/2/index.html" saved
[23/24] File(s) "/Users/happytodev/Sites/cecil/_site/page/1/index.html" saved
[24/24] File(s) "/Users/happytodev/Sites/cecil/_site/blog/page/1/index.html" saved
Saving pages done in 10 ms (352 b)
Built in 445 ms (12.43 mb)
Done 🎉
Server process: /Users/happytodev/Library/Application Support/Herd/bin/php82 -S localhost:8000 -t /Users/happytodev/Sites/cecil/_site /Users/happytodev/Sites/cecil/.cecil/router.php
Starting server (localhost:8000)...
Server is not ready.`

And if I try to launch the last command directly in terminal : 

<img width="966" alt="image" src="https://github.com/Cecilapp/Cecil/assets/425998/ed675b62-d808-4d3a-84b3-a8e6730ef1c7">

And the same with the build command, even if cecil cli said everything ok at this step 😱

<img width="969" alt="image" src="https://github.com/Cecilapp/Cecil/assets/425998/2d5288dd-d0f2-40c9-a34a-dc1217d5d757">

The path with whitespace 'Application Support' seems to be the problem, because if I enter this (with quote), it works : 

<img width="963" alt="image" src="https://github.com/Cecilapp/Cecil/assets/425998/fb0cf1a2-2f03-4f06-861e-4868ea682db7">

Hope it helps you Arnaud !

**Comment by ArnaudLigny** [comment]
Thanks a lot @happytodev for your feedback. Could you try the last release? https://github.com/Cecilapp/Cecil/releases/tag/8.3.1

**Comment by happytodev** [comment]
Hello, 

Yes, now it works correctly.
Thank you for your time Arnaud.

Last little thing, when I tried to update with brew, it answers this 

<img width="872" alt="image" src="https://github.com/Cecilapp/Cecil/assets/425998/b5802fd1-7cfa-4a85-81a1-1e7d7ff557c2">

Is there a propagation time ?

**Comment by ArnaudLigny** [comment]
My bad: I was very tired last night and I forgot to bump the Brew tap... It's done.

**Comment by happytodev** [comment]
No problem, you did a great work, thank you.

I've just tried, but I have the same answer

<img width="699" alt="image" src="https://github.com/Cecilapp/Cecil/assets/425998/165da4a8-e9b0-4461-9332-a427109671b1">

May be I forgot something ?

**Comment by happytodev** [comment]
Yes my bad. Everything is ok now. Thank you.
